web:
        build: .
        command: python3 -u app.py
        ports:
                - "5000:5000"
        volumes:
                - .:/src
        links:
                - db
db:
        image: mongo:4.0.4
        volumes: 
                - data:/data
        
